// @ts-check
const fs = require('fs');
const path = require('path');

// The `docusaurus-plugin-typedoc` plugin generates the API markdown pages and a
// companion `typedoc-sidebar.cjs` file inside the docs `out` directory. On a
// truly clean build that file may not exist yet at the moment Docusaurus first
// evaluates this module, so we require it defensively and fall back to an
// autogenerated sidebar. Once the plugin has run, the pretty TypeDoc sidebar is
// used instead.
const typedocSidebarPath = path.join(__dirname, 'docs', 'typedoc-sidebar.cjs');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
let sidebars;

if (fs.existsSync(typedocSidebarPath)) {
  // eslint-disable-next-line import/no-dynamic-require, global-require
  const typedocSidebar = require(typedocSidebarPath);
  sidebars = {
    apiSidebar: [
      {
        type: 'category',
        label: 'API Reference',
        link: { type: 'doc', id: 'index' },
        collapsible: false,
        items: typedocSidebar,
      },
    ],
  };
} else {
  sidebars = {
    apiSidebar: [{ type: 'autogenerated', dirName: '.' }],
  };
}

module.exports = sidebars;
